### ISSUE TITLE
No such module FLXView in playground

### ISSUE THREAD

**Issue by AndrewSB** [robb/FLXView#1]
![screen shot 2015-05-08 at 8 33 19 pm](https://cloud.githubusercontent.com/assets/3814772/7548074/7cb88b06-f5c1-11e4-88bf-49e405dad687.png)

**Comment by robb** [comment]
Try building the FLXView.framework target at least once before, then close an re-open the playground.

**Comment by robb** [comment]
Closing this one for lack of activity. Hopefully the playground integrations improves soon but I don't think there's much I can do.

**Comment by royalicing** [comment]
I have same issue after building, closing and reopening Xcode. Really strange. Any chance of a screenshot or video of the playground?

**Comment by nubbel** [comment]
@BurntCaramel I couldn't get it to work either, so I created an app from the playground. Please find it here: https://github.com/nubbel/FLXViewExample
