### ISSUE TITLE
Sizing tableview/collectionview cells

### ISSUE THREAD

**Issue by foulkesjohn** [robb/FLXView#3]
I'm trying (and failing) to get dynamically sized table cells using FLXView. Any help would be appreciated. I have a simple test project: https://github.com/foulkesjohn/FLXViewTableTest.

Should I just be able to throw views at the FLXView and then ask it for a size? Is this possible with FLXView?

**Comment by robb** [comment]
Are you setting `estimatedRowHeight` to something non-zero?

**Comment by foulkesjohn** [comment]
I'm not using estimated heights as I'm trying to support iOS 7 as wel :(

**Comment by robb** [comment]
Sorry, don't really know how to do it for iOS 7 then, but I don't think `FLXView` changes anything about how the sizing works.

**Comment by champo** [comment]
@foulkesjohn I've looked through your code and found that removing [this line](https://github.com/foulkesjohn/FLXViewTableTest/blob/master/FLXVViewTableTest/TestCell.m#L22) makes it work correctly.

**Comment by robb** [comment]
:+1: @champo

**Comment by foulkesjohn** [comment]
Thanks for looking @champo thats what I was after :)
